### PR TITLE
Fix (#229):  Fix upload

### LINKED ISSUE #272: Dialog box styling fixes
- Dialog box has multiple scrollbars
- Bottom right close button technically isn't required, so add a default close button in top right in case it gets left off/hard to spot
- Fix button to match app styles

Note: These have already been addressed, but making a separate ticket for PR

### PR DESCRIPTION
**Pull request by tholulomo**
Merged #272 changes to fix CI failures. Add additional bug fixes
closes #272

### CODE REVIEW

File: app/src/pages/explorer/Curate.vue [hunk 1]
```diff
@@ -39,7 +39,16 @@
                                 </div>
                             </router-link>
                         </div>
-                        <!-- <div class="md-layout-item">&nbsp;</div> -->
+                        <div class="md-layout-item md-layout-item_card">
+                            <router-link to="" v-slot="{navigate, href}" custom>
+                                <div class="teams_container explorer_page-nav-card md-layout-item_card" :href="href" @click="navigate">
+                                    <md-icon class="explorer_page-nav-card_icon">article</md-icon>
+                                    <span class="explorer_page-nav-card_text">Submit FEA Templates</span>
```
Comment (aswallace) [inline app/src/pages/explorer/Curate.vue:46]: I may have misunderstood, but I thought Bingyin said that FEA uses the same script as XML so aside from needing to add a link to the blank template and to compression in supplementary materials we can use the same spreadsheet upload page

File: app/src/pages/explorer/Curate.vue [hunk 2]
```diff
@@ -39,7 +39,16 @@
...
+                                    <p class="md-layout-item_para md-layout-item_para_fl">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor magna aliqua.
```
Comment (aswallace) [inline app/src/pages/explorer/Curate.vue:47]: We should probably remove the placeholder text or at least hide it?

File: app/src/assets/css/modules/_pages.scss [hunk 3]
```diff
@@ -392,7 +392,12 @@
 
     p {
         padding: 0 20em;
-
+        a{
+            a{
+                color: $tertiary !important;
```
Comment (aswallace) [inline app/src/assets/css/modules/_pages.scss:397]: The green on white is a little hard to see
