### PR TITLE
#373 fix chart editing and deletion

### LINKED ISSUE #373: ES deletes all charts instead of just one
**Describe the bug**
When editing a chart, ES deletes all existing charts instead of just the old version of the specified chart

**To Reproduce**
1. Create a new chart and save
2. Without leaving the editor page, make a change and re-save
3. ES deletes all charts instead of just the old version of the current chart

**Expected behavior**
ES should only delete the currently open chart (so that we don't end up with duplicate charts)

### PR DESCRIPTION
**Pull request by aswallace**
Fixes multiple issues with charts:
- Make charts editable from both their individual pages and the gallery
- Allow admins to delete charts (with dialog box confirmation)
- Fix the issue where elastic search would delete all charts from cache instead of just the exact match
- Standardize chart URIs to be consistent with previous implementation
- Make sure shareable chart links are permanent
- Add `(.*)` to chart routes for backwards compatibility with any purl.org charts left on QA (since otherwise Vue router misinterprets `/` symbols in URIs)

fixes #373 #372 
closes #374 (open PR that has been merged into this one)

### CODE REVIEW

File: app/src/pages/explorer/chart/editor/Chart.vue [hunk 1]
```diff
@@ -107,9 +107,11 @@ export default {
         title: null,
         description: null
       },
-      actionType: 'Save Chart'
+      actionType: 'Save Chart',
+      sumbmittedIdentifier: undefined
```
Comment (aswallace) [inline app/src/pages/explorer/chart/editor/Chart.vue:111]: Just noticed this typo, will fix asap

**Review by tholulomo — APPROVED** [review]
