### PR TITLE
fix(#387): Curation Improvements

### LINKED ISSUE #387: Xlsx curation stepper form - UI improvements
#### Suggested usability improvements for the stepper form UI
From discussion with Marc 5/10/23. These won't be implemented immediately, but are ideas to consider after the MVP (#378) is complete. 

The essential tradeoff consideration here is automation/maintainability vs. customization/usability.

- Add a dropdown above the header that **allows users to jump to a specific step** (or at least view all steps)
- **Make some fields required**, and have them start open or emphasized. Must edit the json for this 
- Provide a Github-style **outline in a side panel** that allows users to view where they are in the full step tree
- Initial **series of questions to limit the number of steps** a user has to view: "Do you have any mechanical properties to report? E.g., tensile, flexural, compression, shear, fracture, impact, hardness" etc.
- Some of the quantitative value entries make it look like there’s more needed than is actually needed (some fields are optional), and having fields for both note and description are redundant/confusing without explanation to user
- **Pin header** for expandable fields so that the header stays visible as user scrolls?
- Ability **remove/hide field** that they won’t have any input for, or at least disable (gray it out) so that it can be re-enabled
- **Reduce number of steps** shown depending on page/screen size

### PR DESCRIPTION
**Pull request by tholulomo**
Implemented enhancements to the curation form, which include adding a unit of measure to the input, updating unit tests, and incorporating the new FEA spreadsheet entries into the Base JSON object.

closes #387

### CODE REVIEW

File: app/src/pages/explorer/curate/validlist/XlsList.vue [hunk 1]
```diff
@@ -67,7 +67,7 @@
                       <md-field style="align-items: baseline;">
                         <p style="margin-right: 4px;font-weight: bold;">FieldName:</p>
                         <md-input v-model="fieldName" id="fieldName"></md-input>
-                        <span class="md-helper-text">Section::Subsection::Unit</span>
+                        <!-- <span class="md-helper-text">Unit</span> -->
```
Comment (aswallace) [inline app/src/pages/explorer/curate/validlist/XlsList.vue:70]: Could this commented out part be removed or is it a todo?

**Review by aswallace — APPROVED** [review]
Tested locally, looks good
