### PR TITLE
fix (#235): Update Drawer with Curation

### LINKED ISSUE #235: Update Drawer with Curation
The current drawer is missing a curation menu. Materialsmine no longer uses just upload but curation. This ticket seeks to update the text shown when the drawer is displayed.

Write unit tests if doesn't exist.

Screen Shot 2022-07-25 at 2 19 18 PM

### PR DESCRIPTION
**Pull request by tholulomo**
Update side drawer with curation menu options

close #235

### CODE REVIEW

File: app/src/components/Drawer.vue [hunk 1]
```diff
@@ -49,13 +49,19 @@
...
         <md-list slot="md-expand">
-          <router-link :to="'/nm/xml-uploader'" v-slot="{navigate, href}" custom>
-            <md-list-item :href="href" @click="navigate"  class="md-inset">XML-Based Upload</md-list-item>
+          <router-link :to="''" v-slot="{navigate, href}" custom>
+            <md-list-item :href="href" @click="navigate"  class="md-inset">Upload a spreadsheet</md-list-item>
           </router-link>
-          <router-link :to="'/mm/dataset-entry-form'" v-slot="{navigate, href}" custom>
-            <md-list-item :href="href" @click="navigate"  class="md-inset">Direct Dataset Entry Form</md-list-item>
+          <router-link :to="''" v-slot="{navigate, href}" custom>
+            <md-list-item :href="href" @click="navigate"  class="md-inset">Fill a Form</md-list-item>
```
Comment (aswallace) [inline app/src/components/Drawer.vue:58]: My only suggestion is to lower case "form" so it matches the capitalization of the other menu items

**Review by aswallace — APPROVED** [review]
