### PR TITLE
chore(#155): Fixes

### LINKED ISSUE #155: Add docker Ignore
Add a .dockerignore for this build. Currently, the entire node_modules directory is copied into the container as part of the build context, which is almost 1GB. Also, include package-lock.json in the files to ignore.

### LINKED ISSUE #177: Add 404 component
In the frontend app, when the user navigates to an unknown route, they are redirected to one of the homepages.
This can be somewhat annoying e.g. if you have a typo in your URL, you have to retype the path instead of making a small correction.
We should display a "page not found" component when the URL doesn't match a known route: https://router.vuejs.org/guide/essentials/dynamic-matching.html#catch-all-404-not-found-route

### LINKED ISSUE #182: Search not rerending

### LINKED ISSUE #202: Data explorer - open search
Users should be able to run a custom search in data explorer rather than having to select an autosuggested entry.

### LINKED ISSUE #206: Import query results into data voyager
Change button to bring query results into data voyager.  Currently, there is a box in the upper right with a checkmark that isn't intuitive for many users (see picture)
Screen Shot 2022-05-17 at 5 13 39 PM
.

### LINKED ISSUE #208: Implement short-term caching

### PR DESCRIPTION
**Pull request by tholulomo**
Add docker ignore, add a 404 page, search rendering bug fixes, fix pixel unit testing, change datavoyager link to a button, with additional bug fixes

closes #177 
closes #155 
closes #206
closes #182 
closes #208 
closes #202

### CODE REVIEW

**Review by aswallace — COMMENTED** [review]
Main comment is that the /explorer/create route has been changed to /explorer/curate in some places but not in others (e.g., router/module/explorer.js

File: app/src/pages/explorer/parameterized-query/parameterized-query-page.vue [hunk 1]
```diff
@@ -96,14 +78,26 @@
...
               Auto Refresh
             </md-switch>
+            <div class="button-row">
+              <div>
+                <router-link :to="{ name: 'NewChartDataVoyager' }" target="_blank">
+                  <button
+                    class="btn btn--primary"
+                    @click="selectQueryForVizEditor()"
+                  >
+                    Open in Datavoyer
```
[the remark this answers is not in the document]
Comment (tholulomo) [reply app/src/pages/explorer/parameterized-query/parameterized-query-page.vue:96]: @aswallace thanks for pointing this out 🙂

File: app/src/components/explorer/Header.vue [hunk 2]
```diff
@@ -22,13 +22,13 @@
       <div class="md-toolbar-row u_margin-top-med">
         <md-tabs class="md-primary" id="reset_tab_bg">
           <router-link  class="tabs" to="/explorer" v-slot="{navigate, href}" custom>
-              <md-tab :href="href" @click="navigate" id="tab-home" md-label="Search"> </md-tab>
+              <md-tab :href="href" @click="href === '/explorer' ? setSearching : navigate" id="tab-home" md-label="Search"> </md-tab>
           </router-link>
           <router-link class="tabs" to="/explorer/visualization" v-slot="{navigate, href}" custom>
               <md-tab :href="href" @click="navigate" id="tab-pages" md-label="Visualization"> </md-tab>
           </router-link>
           <router-link class="tabs" to="/explorer/create" v-slot="{navigate, href}" custom>
```
[the remark this answers is not in the document]
Comment (tholulomo) [reply app/src/components/explorer/Header.vue]: @aswallace I updated the code to use curate instead of create.

**Review by aswallace — APPROVED** [review]
Only comment is that there's still a link to `/create` in `pages/explorer/Home.vue`. Otherwise approved

File: app/src/pages/explorer/Home.vue [hunk 3]
```diff
@@ -78,6 +78,14 @@ export default {
   },
```
Comment (aswallace) [inline app/src/pages/explorer/Home.vue:78]: I can't leave a comment on the actual line, but it's on line 69: `link: 'explorer/create'`

Comment (tholulomo) [reply app/src/pages/explorer/Home.vue:78]: fixed

File: app/.dockerignore [hunk 4]
```diff
@@ -0,0 +1 @@
+node_modules
```
Comment (stouffers) [inline app/.dockerignore:1]: #155 mentions ignoring package-lock.json as well.  I'm not sure exactly why, since we are committing package-lock in this repo
