### PR TITLE
Fix (#9): Metamine Visualization Refactor

### LINKED ISSUE #388: MetaMaterial NU Page 1 -- add Pairwise Plot Page
Describe the task
MetaMaterial NU is an integration with NU's own material visualization website

Tasks Completed: 
1. Add a new page under 'visualization'
2. Add pairwise plot, material structure plot, poisson's ratio, and young's module plots
3. Add restful API that connects to AWS S3 bucket

### LINKED ISSUE #394: MetamaterialsNU add data-selectors
Description 
Add axis selectors to scatter page and histogram page
Add routing

### LINKED ISSUE #397: Error with Youngs Unit Test
**Describe the bug**
TypeError: window.URL.createObjectURL is not a function under components/youngs.spec.js

### LINKED ISSUE #426: Bug fix for VisualizationNU
**Describe the bug**
pairwise plot: redundant scrollbar 
tooltip style: overlapped
scatter plot: fix zoom and brush, enabled get knn results 
histogram plot: tooltip and mean line fix

### LINKED ISSUE #432: replace antd usage with vue-material
Remove antd usage on DataSelector and RangeSelector

### LINKED ISSUE #433: Write tests for VisualizationNU components
Write tests for the following: 
Pages: pairwise plot page, scatter plot page, histogram plot page 
Components: data-selector, range-selector, youngs plot, poissons plot, pairwise plot, scatter plot, histogram plot

### PR DESCRIPTION
**Pull request by tholulomo**
This pull request focuses on the following enhancements:
1. Replacing AWS and AWS controller with internal object storage.
2. Refactoring duplicate CSS styles.
3. Improving components and component logic.
4. Adding unit tests for components and pages.

resolves #433, resolves #432, resolves #426, resolves #397, resolves #388, resolves #394

### CODE REVIEW

File: app/src/components/metamine/visualizationNU/DataSelector.vue [hunk 1]
```diff
@@ -27,16 +16,10 @@
...
-            >
+            <div class="u--layout-flex u--layout-flex-column" style="margin: 5px 0px">
                 <md-field>
                     <label for="xAxis">X-axis</label>
-                    <md-select
-                        v-model="query1"
-                        style="width: 100%"
-                        name="xAxis"
-                    >
+                    <md-select class="u_width--max" v-model="query1" name="xAxis">
```
Comment (aswallace) [inline app/src/components/metamine/visualizationNU/DataSelector.vue:22]: These selectors don't seem to do anything right now

File: app/src/components/metamine/visualizationNU/SaveDataPanel.vue [hunk 2]
```diff
@@ -1,14 +1,8 @@
...
-                display: flex;
-                justify-content: space-between;
-                align-items: center;
-            "
-        >
-            <div class="nuplot-table-title">Save Data Panel</div>
+            class="table-header u_display-flex u--layout-flex-justify-sb u_centralize_items">
+            <div class="nuplot-table-title article_metadata_strong md-title u--padding-zero">Save Data Panel</div>
             <md-button>
                 <download-csv :data="selectedData" name="selected_data.csv">
```
Comment (aswallace) [inline app/src/components/metamine/visualizationNU/SaveDataPanel.vue:7]: Since the table in the "Save Data" dialog box only shows selected data, it would be nice to have a "No data points selected" message instead of just the empty table when no points are selected

**Review by aswallace — APPROVED** [review]
I haven't tested with real minio data yet, but otherwise looks good. Responsiveness for different screen sizes is much better now
